// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEFBRma0ILMH7CTaRPRuGClADy8XRFtEk',
    appId: '1:866094613641:web:b7e374e06a65f1d2e63258',
    messagingSenderId: '866094613641',
    projectId: 'flutterauthen-27a39',
    authDomain: 'flutterauthen-27a39.firebaseapp.com',
    storageBucket: 'flutterauthen-27a39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Ho5vpz1yUom9bPL3TQm0g7w7p27D9E8',
    appId: '1:866094613641:android:8b1a96f42211be0ce63258',
    messagingSenderId: '866094613641',
    projectId: 'flutterauthen-27a39',
    storageBucket: 'flutterauthen-27a39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdwg9LEYP-xwO3DIuRk68ZZCVwy-oJeOU',
    appId: '1:866094613641:ios:d52825049e412592e63258',
    messagingSenderId: '866094613641',
    projectId: 'flutterauthen-27a39',
    storageBucket: 'flutterauthen-27a39.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdwg9LEYP-xwO3DIuRk68ZZCVwy-oJeOU',
    appId: '1:866094613641:ios:d7f0354575ba2d99e63258',
    messagingSenderId: '866094613641',
    projectId: 'flutterauthen-27a39',
    storageBucket: 'flutterauthen-27a39.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
